# -*- coding: utf-8 -*-
"""Bio_inspired_SHM_full_and_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JuiQMari7wqvPQdem-uORXg7qjGVR5xC
"""

# =========================================================
# INSTALL REQUIRED LIBRARIES
# =========================================================
# RUN ONLY ONCE IN COLAB / NOTEBOOK
!pip install -q numpy pandas matplotlib seaborn scikit-learn tensorflow shap streamlit streamlit-autorefresh pyngrok

# =========================================================
# IMPORT LIBRARIES
# =========================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import time
import warnings
warnings.filterwarnings("ignore")
# =========================================================
# MACHINE LEARNING IMPORTS
# =========================================================
from sklearn.ensemble import IsolationForest
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve
)
# =========================================================
# DEEP LEARNING IMPORTS
# =========================================================
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Dense,
    Dropout,
    BatchNormalization
)
from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau
)
# =========================================================
# FIX RANDOMNESS
# =========================================================
np.random.seed(42)
tf.random.set_seed(42)

# =========================================================
# IMPROVED REALISTIC SENSOR GENERATION
# =========================================================
def generate_normal_data(t):
    # -----------------------------------------------------
    # OCCUPANCY
    # -----------------------------------------------------
    occupancy = np.random.randint(20, 100)
    # -----------------------------------------------------
    # TEMPERATURE
    # OCCUPANCY + ENVIRONMENTAL EFFECT
    # -----------------------------------------------------
    temp = (
        22
        + 0.03 * occupancy
        + 3 * np.sin(t / 20)
        + np.random.normal(0, 0.7)
    )
    # -----------------------------------------------------
    # HUMIDITY
    # CORRELATED WITH OCCUPANCY
    # -----------------------------------------------------
    humidity = (
        50
        + 0.02 * occupancy
        + 8 * np.sin(t / 25)
        + np.random.normal(0, 1.5)
    )
    # -----------------------------------------------------
    # VIBRATION
    # OCCUPANCY-DEPENDENT
    # -----------------------------------------------------
    vibration = (
        1.5
        + 0.01 * occupancy
        + 0.5 * np.sin(t / 15)
        + np.random.normal(0, 0.12)
    )
    # -----------------------------------------------------
    # STRAIN
    # CORRELATED WITH VIBRATION
    # -----------------------------------------------------
    strain = (
        4
        + 0.5 * vibration
        + np.random.normal(0, 0.2)
    )
    # -----------------------------------------------------
    # ENERGY CONSUMPTION
    # OCCUPANCY + HVAC LOAD
    # -----------------------------------------------------
    energy = (
        180
        + occupancy * 2
        + temp * 4
        + np.random.normal(0, 4)
    )
    return {
        "temp": temp,
        "humidity": humidity,
        "vibration": vibration,
        "strain": strain,
        "occupancy": occupancy,
        "energy": energy
    }

# =========================================================
# ADVANCED PREPROCESSING
# =========================================================
def preprocess(data):
    # -----------------------------------------------------
    # CLIP UNREALISTIC VALUES
    # -----------------------------------------------------
    data["temp"] = np.clip(
        data["temp"],
        10,
        50
    )
    data["humidity"] = np.clip(
        data["humidity"],
        20,
        100
    )
    # =====================================================
    # BASIC FEATURE ENGINEERING
    # =====================================================
    data["temp_norm"] = (
        data["temp"] / 50
    )
    data["vibration_energy"] = (
        data["vibration"] *
        data["energy"]
    )
    data["temp_humidity"] = (
        data["temp"] *
        data["humidity"]
    )
    data["strain_vibration"] = (
        data["strain"] *
        data["vibration"]
    )
    # =====================================================
    # ADVANCED RELATIONSHIP FEATURES
    # =====================================================
    # -----------------------------------------------------
    # HVAC EFFICIENCY
    # -----------------------------------------------------
    data["temp_energy_ratio"] = (
        data["temp"] /
        (data["energy"] + 1e-6)
    )
    # -----------------------------------------------------
    # STRUCTURAL CONSISTENCY
    # -----------------------------------------------------
    data["vibration_strain_ratio"] = (
        data["vibration"] /
        (data["strain"] + 1e-6)
    )
    # -----------------------------------------------------
    # OCCUPANCY ENERGY BEHAVIOR
    # -----------------------------------------------------
    data["occupancy_energy_ratio"] = (
        data["occupancy"] /
        (data["energy"] + 1e-6)
    )
    # -----------------------------------------------------
    # ENVIRONMENTAL LOAD
    # -----------------------------------------------------
    data["environmental_load"] = (
        data["temp"] *
        data["humidity"]
    ) / 100
    return data

# =========================================================
# CREATE NORMAL TRAINING DATASET
# =========================================================
normal_dataset = []
for t in range(2000):
    data = generate_normal_data(t)
    data = preprocess(data)
    normal_dataset.append(
        list(data.values())
    )
normal_dataset = np.array(
    normal_dataset
)
print(
    "Normal Dataset Shape:",
    normal_dataset.shape
)

# =========================================================
# IMPROVED TEMPORAL ANOMALY GENERATION
# =========================================================
test_dataset = []
test_labels = []
# ---------------------------------------------------------
# TEMPORAL MEMORY VARIABLES
# ---------------------------------------------------------
anomaly_duration = 0
current_anomaly = None
# ---------------------------------------------------------
# ANOMALY SEVERITY MEMORY
# ---------------------------------------------------------
severity_growth = 0
for t in range(1000):
    data = generate_normal_data(t)
    label = 0
    # -----------------------------------------------------
    # START NEW ANOMALY
    # -----------------------------------------------------
    if anomaly_duration == 0:
        # -------------------------------------------------
        # LOWER ANOMALY FREQUENCY
        # -------------------------------------------------
        if np.random.rand() < 0.08:
            current_anomaly = np.random.choice([
                "overheating",
                "humidity",
                "vibration",
                "strain",
                "energy",
                "multi"
            ])
            # -------------------------------------------------
            # TEMPORAL PERSISTENCE
            # -------------------------------------------------
            anomaly_duration = np.random.randint(
                5,
                15
            )
            severity_growth = 0
    # -----------------------------------------------------
    # APPLY TEMPORAL ANOMALY
    # -----------------------------------------------------
    if anomaly_duration > 0:
        label = 1
        # -------------------------------------------------
        # GRADUAL DEGRADATION
        # -------------------------------------------------
        severity_growth += 0.15
        severity = min(
            1.0 + severity_growth,
            3.5
        )
        # -------------------------------------------------
        # OVERHEATING
        # -------------------------------------------------
        if current_anomaly == "overheating":
            data["temp"] += (
                severity *
                np.random.uniform(1.5, 3)
            )
        # -------------------------------------------------
        # HUMIDITY SPIKE
        # -------------------------------------------------
        elif current_anomaly == "humidity":
            data["humidity"] += (
                severity *
                np.random.uniform(4, 8)
            )
        # -------------------------------------------------
        # STRUCTURAL INSTABILITY
        # -------------------------------------------------
        elif current_anomaly == "strain":
            data["strain"] += (
                severity *
                np.random.uniform(1.5, 3)
            )
        # -------------------------------------------------
        # ABNORMAL VIBRATION
        # -------------------------------------------------
        elif current_anomaly == "vibration":
            data["vibration"] += (
                severity *
                np.random.uniform(1, 2)
            )
        # -------------------------------------------------
        # ENERGY INEFFICIENCY
        # -------------------------------------------------
        elif current_anomaly == "energy":
            data["energy"] += (
                severity *
                np.random.uniform(40, 80)
            )
        # -------------------------------------------------
        # MULTI-VARIABLE ANOMALY
        # -------------------------------------------------
        elif current_anomaly == "multi":
            data["temp"] += (
                severity *
                np.random.uniform(1, 2)
            )
            data["humidity"] += (
                severity *
                np.random.uniform(3, 6)
            )
            data["energy"] += (
                severity *
                np.random.uniform(30, 60)
            )
            data["vibration"] += (
                severity *
                np.random.uniform(0.5, 1.5)
            )
        # -------------------------------------------------
        # REDUCE DURATION
        # -------------------------------------------------
        anomaly_duration -= 1
    # -----------------------------------------------------
    # PREPROCESS DATA
    # -----------------------------------------------------
    data = preprocess(data)
    test_dataset.append(
        list(data.values())
    )
    test_labels.append(label)
# ---------------------------------------------------------
# CONVERT TO NUMPY
# ---------------------------------------------------------
test_dataset = np.array(test_dataset)
test_labels = np.array(test_labels)
print(
    "Improved Temporal Dataset Created"
)
print(
    "Anomaly Ratio:",
    np.mean(test_labels)
)

# =========================================================
# SCALE DATA
# =========================================================
scaler = StandardScaler()
train_scaled = scaler.fit_transform(
    normal_dataset
)
test_scaled = scaler.transform(
    test_dataset
)

# =========================================================
# IMPROVED ISOLATION FOREST
# =========================================================
iso_model = IsolationForest(
    # -----------------------------------------------------
    # HIGHER CONTAMINATION
    # IMPROVES RECALL
    # -----------------------------------------------------
    contamination=0.10,
    # -----------------------------------------------------
    # MORE TREES
    # BETTER GENERALIZATION
    # -----------------------------------------------------
    n_estimators=300,
    # -----------------------------------------------------
    # RANDOMNESS CONTROL
    # -----------------------------------------------------
    random_state=42,
    # -----------------------------------------------------
    # USE ALL FEATURES
    # -----------------------------------------------------
    max_features=1.0,
    # -----------------------------------------------------
    # AUTO SAMPLE SELECTION
    # -----------------------------------------------------
    max_samples='auto'
)
# =========================================================
# TRAIN ONLY ON NORMAL DATA
# =========================================================
iso_model.fit(
    train_scaled
)
print(
    "Improved Isolation Forest Trained"
)

# =========================================================
# SHAP EXPLANATIONS
# =========================================================
explainer = shap.Explainer(
    iso_model.decision_function,
    train_scaled[:100]
)
sample_shap = explainer(
    test_scaled[:20]
)
# ---------------------------------------------------------
# SHAP SUMMARY PLOT
# ---------------------------------------------------------
shap.summary_plot(
    sample_shap.values,
    test_scaled[:20],
    feature_names=[
        "temp",
        "humidity",
        "vibration",
        "strain",
        "occupancy",
        "energy",
        "temp_norm",
        "vibration_energy",
        "temp_humidity",
        "strain_vibration",
        "temp_energy_ratio",
        "vibration_strain_ratio",
        "occupancy_energy_ratio",
        "environmental_load"
    ]
)

# =========================================================
# ENHANCED AUTOENCODER
# =========================================================
autoencoder = Sequential([
    # =====================================================
    # ENCODER
    # =====================================================
    Dense(
        128,
        activation='relu',
        input_shape=(
            train_scaled.shape[1],
        )
    ),
    BatchNormalization(),
    Dropout(0.35),
    Dense(
        64,
        activation='relu'
    ),
    BatchNormalization(),
    Dropout(0.30),
    Dense(
        32,
        activation='relu'
    ),
    BatchNormalization(),
    Dense(
        16,
        activation='relu'
    ),
    # =====================================================
    # LATENT SPACE
    # =====================================================
    Dense(
        3,
        activation='tanh'
    ),
    # =====================================================
    # DECODER
    # =====================================================
    Dense(
        16,
        activation='relu'
    ),
    BatchNormalization(),
    Dense(
        32,
        activation='relu'
    ),
    BatchNormalization(),
    Dense(
        64,
        activation='relu'
    ),
    BatchNormalization(),
    Dense(
        128,
        activation='relu'
    ),
    Dense(
        train_scaled.shape[1],
        activation='linear'
    )
])
# =========================================================
# COMPILE MODEL
# =========================================================
autoencoder.compile(
    optimizer='adam',
    loss='mae'
)
print(
    "Enhanced Autoencoder Ready"
)

# =========================================================
# ADVANCED OVERFITTING PREVENTION
# =========================================================
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=8,
    restore_best_weights=True
)
reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=4,
    min_lr=1e-5
)

# =========================================================
# TRAIN ADVANCED AUTOENCODER
# =========================================================
history_ae = autoencoder.fit(
    train_scaled,
    train_scaled,
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    shuffle=True,
    callbacks=[
        early_stop,
        reduce_lr
    ],
    verbose=1
)
print(
    "Advanced Autoencoder Training Completed"
)

# =========================================================
# IMPROVED RECONSTRUCTION THRESHOLD
# =========================================================
recon = autoencoder(
    train_scaled,
    training=False
).numpy()
# ---------------------------------------------------------
# MAE RECONSTRUCTION LOSS
# ---------------------------------------------------------
losses = np.mean(
    np.abs(
        train_scaled - recon
    ),
    axis=1
)
# ---------------------------------------------------------
# LOWER THRESHOLD
# IMPROVES ANOMALY DETECTION
# ---------------------------------------------------------
threshold = np.percentile(
    losses,
    85
)
print(
    "Improved Threshold:",
    threshold
)

# =========================================================
# IMPROVED RULE-BASED DETECTION
# =========================================================
def rule_based_detection(data):
    score = 0
    alerts = []
    risk_levels = []
    # =====================================================
    # TEMPERATURE RISK
    # =====================================================
    if data["temp"] > 31:
        temp_risk = (
            data["temp"] - 31
        ) / 3
        score += temp_risk
        alerts.append(
            "Overheating Detected"
        )
        risk_levels.append(
            "HIGH"
        )
    # =====================================================
    # HUMIDITY RISK
    # =====================================================
    if data["humidity"] > 72:
        humidity_risk = (
            data["humidity"] - 72
        ) / 6
        score += humidity_risk
        alerts.append(
            "Humidity Spike"
        )
        risk_levels.append(
            "MEDIUM"
        )
    # =====================================================
    # VIBRATION RISK
    # =====================================================
    if data["vibration"] > 3.5:
        vibration_risk = (
            data["vibration"] - 3.5
        )
        score += vibration_risk
        alerts.append(
            "Abnormal Structural Vibration"
        )
        risk_levels.append(
            "HIGH"
        )
    # =====================================================
    # STRAIN RISK
    # =====================================================
    if data["strain"] > 6.5:
        strain_risk = (
            data["strain"] - 6.5
        )
        score += strain_risk
        alerts.append(
            "Structural Instability"
        )
        risk_levels.append(
            "CRITICAL"
        )
    # =====================================================
    # ENERGY RISK
    # =====================================================
    if (
        data["energy"] > 380
        and data["temp"] > 30
    ):
        energy_risk = (
            data["energy"] - 380
        ) / 35
        score += energy_risk
        alerts.append(
            "Energy Efficiency Problem"
        )
        risk_levels.append(
            "HIGH"
        )
    # =====================================================
    # ENVIRONMENTAL FUSION
    # =====================================================
    if (
        data["temp"] > 31
        and data["humidity"] > 72
    ):
        score += 4
        alerts.append(
            "Environmental Multi-Risk"
        )
        risk_levels.append(
            "CRITICAL"
        )
    # =====================================================
    # STRUCTURAL FUSION
    # =====================================================
    if (
        data["vibration"] > 3.5
        and data["strain"] > 6.5
    ):
        score += 5
        alerts.append(
            "Critical Structural Risk"
        )
        risk_levels.append(
            "SEVERE"
        )
    return score, alerts, risk_levels

# =========================================================
# ISOLATION FOREST PREDICTIONS
# =========================================================
iso_preds = (
    iso_model.predict(test_scaled) == -1
).astype(int)
iso_acc = accuracy_score(
    test_labels,
    iso_preds
)
print(
    "Isolation Forest Accuracy:",
    iso_acc
)

# =========================================================
# AUTOENCODER PREDICTIONS
# =========================================================
recon_test = autoencoder.predict(
    test_scaled,
    verbose=0
)
test_losses = np.mean(
    (test_scaled - recon_test) ** 2,
    axis=1
)
ae_preds = (
    test_losses > threshold
).astype(int)
ae_acc = accuracy_score(
    test_labels,
    ae_preds
)
print(
    "Autoencoder Accuracy:",
    ae_acc
)

# =========================================================
# RULE-BASED PREDICTIONS
# =========================================================
rule_preds = []
rule_alerts = []
for row in test_dataset:
    data_dict = {
        "temp": row[0],
        "humidity": row[1],
        "vibration": row[2],
        "strain": row[3],
        "occupancy": row[4],
        "energy": row[5]
    }
    score, alerts, risk_levels = (
        rule_based_detection(data_dict)
    )
    rule_alerts.append(alerts)
    rule_preds.append(
        int(score > 0)
    )
rule_preds = np.array(rule_preds)
rule_acc = accuracy_score(
    test_labels,
    rule_preds
)
print(
    "Rule-Based Accuracy:",
    rule_acc
)

# =========================================================
# IMPROVED WEIGHTED FUSION
# =========================================================
# ---------------------------------------------------------
# EXTRA WEIGHT TO AE
# ---------------------------------------------------------
ae_priority = 1.5
rule_priority = 1.2
iso_priority = 1.0
weighted_total = (
    ae_acc * ae_priority
    + rule_acc * rule_priority
    + iso_acc * iso_priority
)
ae_weight = (
    ae_acc * ae_priority
) / weighted_total
rule_weight = (
    rule_acc * rule_priority
) / weighted_total
iso_weight = (
    iso_acc * iso_priority
) / weighted_total
print(
    "Isolation Forest Weight:",
    iso_weight
)
print(
    "Autoencoder Weight:",
    ae_weight
)
print(
    "Rule-Based Weight:",
    rule_weight
)

# =========================================================
# MEMORY-AWARE HYBRID FUSION
# =========================================================
# ---------------------------------------------------------
# SIGMOID NORMALIZATION
# ---------------------------------------------------------
def sigmoid_normalize(x):
    return 1 / (
        1 + np.exp(
            -(
                x - np.mean(x)
            ) / (
                np.std(x) + 1e-6
            )
        )
    )
# ---------------------------------------------------------
# NORMALIZED AE SCORES
# ---------------------------------------------------------
ae_scores = sigmoid_normalize(
    test_losses
)
# ---------------------------------------------------------
# NORMALIZED IF SCORES
# ---------------------------------------------------------
iso_raw_scores = (
    -iso_model.decision_function(
        test_scaled
    )
)
iso_scores = sigmoid_normalize(
    iso_raw_scores
)
# ---------------------------------------------------------
# RULE-BASED SCORES
# ---------------------------------------------------------
rule_scores = []
for row in test_dataset:
    data_dict = {
        "temp": row[0],
        "humidity": row[1],
        "vibration": row[2],
        "strain": row[3],
        "occupancy": row[4],
        "energy": row[5]
    }
    score, _, _ = rule_based_detection(
        data_dict
    )
    rule_scores.append(score)
rule_scores = np.array(rule_scores)
rule_scores = sigmoid_normalize(
    rule_scores
)
# =========================================================
# MEMORY-AWARE FUSION
# =========================================================
final_scores = []
recent_anomaly_memory = []
for i in range(len(test_dataset)):
    score = (
        ae_weight * ae_scores[i]
        +
        iso_weight * iso_scores[i]
        +
        rule_weight * rule_scores[i]
    )
    # -----------------------------------------------------
    # MULTI-RISK AMPLIFICATION
    # -----------------------------------------------------
    if rule_scores[i] > 0.7:
        score += 0.12
    # -----------------------------------------------------
    # ANOMALY MEMORY
    # -----------------------------------------------------
    if len(recent_anomaly_memory) > 5:
        recent_average = np.mean(
            recent_anomaly_memory[-5:]
        )
        # -------------------------------------------------
        # ADAPTIVE SENSITIVITY
        # -------------------------------------------------
        if recent_average > 0.6:
            score += 0.08
    final_scores.append(score)
    # -----------------------------------------------------
    # STORE MEMORY
    # -----------------------------------------------------
    recent_anomaly_memory.append(score)
# ---------------------------------------------------------
# CONVERT TO ARRAY
# ---------------------------------------------------------
final_scores = np.array(final_scores)
# =========================================================
# DYNAMIC THRESHOLD
# =========================================================
hybrid_threshold = np.percentile(
    final_scores,
    65
)
# =========================================================
# FINAL PREDICTIONS
# =========================================================
hybrid_preds = (
    final_scores > hybrid_threshold
).astype(int)
print(
    "Memory-Aware Hybrid Fusion Applied"
)
print(
    "Dynamic Threshold:",
    hybrid_threshold
)

# =========================================================
# HYBRID EVALUATION
# =========================================================
accuracy = accuracy_score(
    test_labels,
    hybrid_preds
)
precision = precision_score(
    test_labels,
    hybrid_preds
)
recall = recall_score(
    test_labels,
    hybrid_preds
)
f1 = f1_score(
    test_labels,
    hybrid_preds
)
# Replace NaN values in final_scores with 0 before calculating roc_auc_score
final_scores = np.nan_to_num(final_scores, nan=0.0)
roc_auc = roc_auc_score(
    test_labels,
    final_scores
)
# =========================================================
# FALSE ALARM RATE
# =========================================================
cm = confusion_matrix(
    test_labels,
    hybrid_preds
)
tn, fp, fn, tp = cm.ravel()
false_alarm_rate = fp / (fp + tn)
print("\n========== FINAL METRICS ==========")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("ROC-AUC:", roc_auc)
print("False Alarm Rate:", false_alarm_rate)

# =========================================================
# DETECTION LATENCY
# =========================================================
start = time.time()
_ = iso_model.predict(test_scaled)
end = time.time()
latency = end - start
print(
    "Detection Latency:",
    latency,
    "seconds"
)

# =========================================================
# CONFUSION MATRIX
# =========================================================
plt.figure(figsize=(6, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=["Normal", "Anomaly"],
    yticklabels=["Normal", "Anomaly"]
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# =========================================================
# ROC CURVE
# =========================================================
fpr, tpr, _ = roc_curve(
    test_labels,
    final_scores
)
plt.figure(figsize=(6, 5))
plt.plot(
    fpr,
    tpr,
    label=f"AUC = {roc_auc:.2f}"
)
plt.plot(
    [0, 1],
    [0, 1],
    linestyle='--'
)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

# =========================================================
# MODEL COMPARISON
# =========================================================
models = [
    "Isolation Forest",
    "Autoencoder",
    "Rule-Based",
    "Hybrid"
]
accuracies = [
    iso_acc,
    ae_acc,
    rule_acc,
    accuracy
]
plt.figure(figsize=(8, 5))
plt.bar(
    models,
    accuracies
)
plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison")
plt.show()

# =========================================================
# RECONSTRUCTION LOSS DISTRIBUTION
# =========================================================
plt.figure(figsize=(8, 5))
plt.hist(
    test_losses,
    bins=50
)
plt.axvline(
    threshold,
    color='red',
    linestyle='--',
    label='Threshold'
)
plt.xlabel("Reconstruction Loss")
plt.ylabel("Frequency")
plt.title("Autoencoder Reconstruction Loss")
plt.legend()
plt.show()

# =========================================================
# SAVE RESULTS TO CSV
# =========================================================
results_df = pd.DataFrame({
    "Actual_Label": test_labels,
    "IsolationForest_Prediction": iso_preds,
    "Autoencoder_Prediction": ae_preds,
    "RuleBased_Prediction": rule_preds,
    "Hybrid_Prediction": hybrid_preds,
    "Final_Risk_Score": final_scores
})
# ---------------------------------------------------------
# SAVE CSV
# ---------------------------------------------------------
results_df.to_csv(
    "hybrid_results.csv",
    index=False
)
print(
    "Results CSV Saved"
)

# =========================================================
# SAVE EVALUATION METRICS
# =========================================================
metrics_df = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1-Score",
        "ROC-AUC",
        "False Alarm Rate"
    ],
    "Value": [
        accuracy,
        precision,
        recall,
        f1,
        roc_auc,
        false_alarm_rate
    ]
})
metrics_df.to_csv(
    "evaluation_metrics.csv",
    index=False
)
print(
    "Evaluation Metrics CSV Saved"
)

# =========================================================
# SAVE CONFUSION MATRIX
# =========================================================
plt.figure(figsize=(6, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=["Normal", "Anomaly"],
    yticklabels=["Normal", "Anomaly"]
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.savefig(
    "confusion_matrix.png",
    dpi=300,
    bbox_inches='tight'
)
plt.show()
print(
    "Confusion Matrix Saved"
)

# =========================================================
# SAVE ROC CURVE
# =========================================================
fpr, tpr, _ = roc_curve(
    test_labels,
    final_scores
)
plt.figure(figsize=(6, 5))
plt.plot(
    fpr,
    tpr,
    label=f"AUC = {roc_auc:.2f}"
)
plt.plot(
    [0, 1],
    [0, 1],
    linestyle='--'
)
plt.xlabel(
    "False Positive Rate"
)
plt.ylabel(
    "True Positive Rate"
)
plt.title(
    "ROC Curve"
)
plt.legend()
plt.savefig(
    "roc_curve.png",
    dpi=300,
    bbox_inches='tight'
)
plt.show()
print(
    "ROC Curve Saved"
)

# =========================================================
# SAVE MODEL COMPARISON GRAPH
# =========================================================
models = [
    "Isolation Forest",
    "Autoencoder",
    "Rule-Based",
    "Hybrid"
]
accuracies = [
    iso_acc,
    ae_acc,
    rule_acc,
    accuracy
]
plt.figure(figsize=(8, 5))
plt.bar(
    models,
    accuracies
)
plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison")
plt.savefig(
    "model_comparison.png",
    dpi=300,
    bbox_inches='tight'
)
plt.show()
print(
    "Model Comparison Graph Saved"
)

# =========================================================
# DETAILED METRICS
# =========================================================
print("\n========== MODEL PERFORMANCE ==========")
print(
    "Accuracy:",
    accuracy
)
print(
    "Precision:",
    precision
)
print(
    "Recall:",
    recall
)
print(
    "F1 Score:",
    f1
)
print(
    "ROC-AUC:",
    roc_auc
)
print(
    "False Alarm Rate:",
    false_alarm_rate
)
# ---------------------------------------------------------
# CONFUSION MATRIX VALUES
# ---------------------------------------------------------
print("\n========== CONFUSION MATRIX ==========")
print(
    "True Negatives:",
    tn
)
print(
    "False Positives:",
    fp
)
print(
    "False Negatives:",
    fn
)
print(
    "True Positives:",
    tp
)

# =========================================================
# HYBRID SCORE DISTRIBUTION
# =========================================================
plt.figure(figsize=(8, 5))
plt.hist(
    final_scores[test_labels == 0],
    bins=40,
    alpha=0.6,
    label="Normal"
)
plt.hist(
    final_scores[test_labels == 1],
    bins=40,
    alpha=0.6,
    label="Anomaly"
)
plt.axvline(
    hybrid_threshold,
    color='red',
    linestyle='--',
    label='Threshold'
)
plt.xlabel(
    "Hybrid Risk Score"
)
plt.ylabel(
    "Frequency"
)
plt.title(
    "Hybrid Score Distribution"
)
plt.legend()
plt.show()

# =========================================================
# CLASS DISTRIBUTION
# =========================================================
normal_count = np.sum(
    test_labels == 0
)
anomaly_count = np.sum(
    test_labels == 1
)
print(
    "Normal Samples:",
    normal_count
)
print(
    "Anomaly Samples:",
    anomaly_count
)
print(
    "Anomaly Percentage:",
    anomaly_count / len(test_labels)
)

# =========================================================
# TEMPORAL PERFORMANCE ANALYSIS
# =========================================================
rolling_scores = pd.Series(
    final_scores
).rolling(
    window=10
).mean()
plt.figure(figsize=(10, 5))
plt.plot(
    rolling_scores,
    label="Rolling Hybrid Risk"
)
plt.plot(
    test_labels,
    alpha=0.5,
    label="Actual Anomaly"
)
plt.xlabel("Time")
plt.ylabel("Risk Score")
plt.title(
    "Temporal Risk Evolution"
)
plt.legend()
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# # =========================================================
# # STREAMLIT DASHBOARD
# # FILE NAME: app.py
# # =========================================================
# # =========================================================
# # IMPORT LIBRARIES
# # =========================================================
# import streamlit as st
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import plotly.express as px
# import time
# # =========================================================
# # PAGE CONFIGURATION
# # =========================================================
# st.set_page_config(
#     page_title="Bio-Inspired Smart Building System",
#     layout="wide"
# )
# # =========================================================
# # TITLE
# # =========================================================
# st.title(
#     "🏢 Bio-Inspired Autonomous Building Health & Energy Management System"
# )
# st.markdown(
#     """
#     Real-Time Hybrid Anomaly Detection using:
#     - Isolation Forest
#     - Autoencoder
#     - Rule-Based Multi-Risk Fusion
#     """
# )
# # =========================================================
# # SIMULATED LIVE SENSOR VALUES
# # =========================================================
# def generate_live_sensor_data():
#     occupancy = np.random.randint(20, 100)
#     temp = (
#         22
#         + 0.03 * occupancy
#         + np.random.normal(0, 1)
#     )
#     humidity = (
#         50
#         + 0.02 * occupancy
#         + np.random.normal(0, 2)
#     )
#     vibration = (
#         1.5
#         + 0.01 * occupancy
#         + np.random.normal(0, 0.2)
#     )
#     strain = (
#         4
#         + 0.5 * vibration
#         + np.random.normal(0, 0.3)
#     )
#     energy = (
#         180
#         + occupancy * 2
#         + temp * 4
#         + np.random.normal(0, 5)
#     )
#     return {
#         "Temperature": round(temp, 2),
#         "Humidity": round(humidity, 2),
#         "Vibration": round(vibration, 2),
#         "Strain": round(strain, 2),
#         "Occupancy": occupancy,
#         "Energy": round(energy, 2)
#     }
# # =========================================================
# # RULE-BASED ALERT ANALYSIS
# # =========================================================
# def analyze_building_risk(data):
#     alerts = []
#     criticality = "NORMAL"
#     suggestions = []
#     risk_score = 0
#     # =====================================================
#     # OVERHEATING
#     # =====================================================
#     if data["Temperature"] > 31:
#         alerts.append(
#             "Overheating Detected"
#         )
#         suggestions.append(
#             "Activate HVAC cooling system"
#         )
#         risk_score += 2
#     # =====================================================
#     # HUMIDITY
#     # =====================================================
#     if data["Humidity"] > 72:
#         alerts.append(
#             "Humidity Spike"
#         )
#         suggestions.append(
#             "Enable dehumidification"
#         )
#         risk_score += 2
#     # =====================================================
#     # STRUCTURAL VIBRATION
#     # =====================================================
#     if data["Vibration"] > 3.5:
#         alerts.append(
#             "Abnormal Structural Vibration"
#         )
#         suggestions.append(
#             "Inspect mechanical systems"
#         )
#         risk_score += 3
#     # =====================================================
#     # STRUCTURAL STRAIN
#     # =====================================================
#     if data["Strain"] > 6.5:
#         alerts.append(
#             "Structural Instability"
#         )
#         suggestions.append(
#             "Perform structural inspection"
#         )
#         risk_score += 4
#     # =====================================================
#     # ENERGY INEFFICIENCY
#     # =====================================================
#     if (
#         data["Energy"] > 380
#         and data["Temperature"] > 30
#     ):
#         alerts.append(
#             "Energy Inefficiency"
#         )
#         suggestions.append(
#             "Optimize HVAC energy consumption"
#         )
#         risk_score += 3
#     # =====================================================
#     # MULTI-RISK FUSION
#     # =====================================================
#     if (
#         data["Temperature"] > 31
#         and data["Humidity"] > 72
#     ):
#         alerts.append(
#             "Environmental Multi-Risk Condition"
#         )
#         suggestions.append(
#             "Reduce thermal and humidity load"
#         )
#         risk_score += 3
#     if (
#         data["Vibration"] > 3.5
#         and data["Strain"] > 6.5
#     ):
#         alerts.append(
#             "Critical Structural Health Risk"
#         )
#         suggestions.append(
#             "Initiate emergency inspection"
#         )
#         risk_score += 5
#     # =====================================================
#     # RISK LEVEL
#     # =====================================================
#     if risk_score >= 8:
#         criticality = "CRITICAL"
#     elif risk_score >= 5:
#         criticality = "HIGH"
#     elif risk_score >= 2:
#         criticality = "MEDIUM"
#     return (
#         risk_score,
#         criticality,
#         alerts,
#         suggestions
#     )
# # =========================================================
# # GENERATE SENSOR DATA
# # =========================================================
# sensor_data = generate_live_sensor_data()
# # =========================================================
# # ANALYZE RISKS
# # =========================================================
# (
#     risk_score,
#     criticality,
#     alerts,
#     suggestions
# ) = analyze_building_risk(sensor_data)
# # =========================================================
# # SENSOR DISPLAY
# # =========================================================
# st.header("📡 Live Building Sensor Values")
# col1, col2, col3 = st.columns(3)
# with col1:
#     st.write(
#         f"🌡 Temperature: {sensor_data['Temperature']} °C"
#     )
#     st.write(
#         f"💧 Humidity: {sensor_data['Humidity']} %"
#     )
# with col2:
#     st.write(
#         f"🏗 Vibration: {sensor_data['Vibration']}"
#     )
#     st.write(
#         f"🧱 Strain: {sensor_data['Strain']}"
#     )
# with col3:
#     st.write(
#         f"👥 Occupancy: {sensor_data['Occupancy']}"
#     )
#     st.write(
#         f"⚡ Energy: {sensor_data['Energy']} kWh"
#     )
# # =========================================================
# # RISK DISPLAY
# # =========================================================
# st.header("🚨 Building Risk Assessment")
# st.write(
#     f"Hybrid Risk Score: {round(risk_score, 2)}"
# )
# # =========================================================
# # CRITICALITY DISPLAY
# # =========================================================
# if criticality == "NORMAL":
#     st.success(
#         "System Status: NORMAL"
#     )
# elif criticality == "MEDIUM":
#     st.warning(
#         "System Status: MEDIUM RISK"
#     )
# elif criticality == "HIGH":
#     st.error(
#         "System Status: HIGH RISK"
#     )
# elif criticality == "CRITICAL":
#     st.error(
#         "System Status: CRITICAL CONDITION"
#     )
# # =========================================================
# # ALERTS
# # =========================================================
# st.header("⚠ Active Alerts")
# if len(alerts) == 0:
#     st.success(
#         "No active anomalies detected"
#     )
# else:
#     for alert in alerts:
#         st.error(alert)
# # =========================================================
# # RECOMMENDATIONS
# # =========================================================
# st.header("🛠 Recommended Corrective Actions")
# if len(suggestions) == 0:
#     st.success(
#         "No corrective action required"
#     )
# else:
#     for suggestion in suggestions:
#         st.write(
#             f"✔ {suggestion}"
#         )
# # =========================================================
# # REAL-TIME SENSOR HISTORY
# # =========================================================
# st.header("📈 Sensor Trend Visualization")
# time_axis = np.arange(50)
# temp_history = (
#     22
#     + 3 * np.sin(time_axis / 5)
#     + np.random.normal(0, 0.5, 50)
# )
# humidity_history = (
#     50
#     + 8 * np.sin(time_axis / 6)
#     + np.random.normal(0, 1, 50)
# )
# energy_history = (
#     250
#     + 30 * np.sin(time_axis / 4)
#     + np.random.normal(0, 5, 50)
# )
# # =========================================================
# # TEMPERATURE TREND
# # =========================================================
# temp_df = pd.DataFrame({
#     "Time": time_axis,
#     "Temperature": temp_history
# })
# fig_temp = px.line(
#     temp_df,
#     x="Time",
#     y="Temperature",
#     title="Temperature Trend"
# )
# st.plotly_chart(
#     fig_temp,
#     use_container_width=True
# )
# # =========================================================
# # HUMIDITY TREND
# # =========================================================
# humidity_df = pd.DataFrame({
#     "Time": time_axis,
#     "Humidity": humidity_history
# })
# fig_humidity = px.line(
#     humidity_df,
#     x="Time",
#     y="Humidity",
#     title="Humidity Trend"
# )
# st.plotly_chart(
#     fig_humidity,
#     use_container_width=True
# )
# # =========================================================
# # ENERGY TREND
# # =========================================================
# energy_df = pd.DataFrame({
#     "Time": time_axis,
#     "Energy": energy_history
# })
# fig_energy = px.line(
#     energy_df,
#     x="Time",
#     y="Energy",
#     title="Energy Consumption Trend"
# )
# st.plotly_chart(
#     fig_energy,
#     use_container_width=True
# )
# # =========================================================
# # HVAC CONTROL FEEDBACK
# # =========================================================
# st.header("❄ Simulated HVAC Feedback")
# if sensor_data["Temperature"] > 31:
#     st.warning(
#         "HVAC Cooling Activated"
#     )
# else:
#     st.success(
#         "HVAC Operating Normally"
#     )
# # =========================================================
# # STRUCTURAL HEALTH STATUS
# # =========================================================
# st.header("🏗 Structural Health Status")
# if sensor_data["Strain"] > 6.5:
#     st.error(
#         "Structural Integrity Warning"
#     )
# else:
#     st.success(
#         "Structural Health Stable"
#     )
# # =========================================================
# # FOOTER
# # =========================================================
# st.markdown("---")
# st.write(
#     "Bio-Inspired Smart Building Monitoring Dashboard"
# )

from pyngrok import ngrok
ngrok.set_auth_token(
    "3E53w4GCtrIPp82IZibYaBX6YXD_39kEF25zLzMcpWDy1tw7V" #generate your own auth token by signing up in https://dashboard.ngrok.com/get-started/your-authtoken
)

!streamlit run app.py &>/content/logs.txt &

public_url = ngrok.connect(8501)
print(public_url)

!cat /content/logs.txt